### ISSUE TITLE
Feature Request: Ability to modify the color balance of imported pictures

### ISSUE THREAD

**Issue by gverma14** [sprang/Inkpad#104]
I'm not sure how many of these would be possible, but I've been intensively using the app the past month for different projects and I was hoping for some potential upgrades:

There is currently no way to modify the color balance of imported pictures. I see you can change how they blend but that's about it. The color change only works for vector objects. 

I wish there was a way to resize (using the scale tool) something to be a specific pixel width and pixel height

Currently the scale tool does not snap to any grid points or edges (or does not seem to) when scaling. Is it possible this could be modified?

There should be a way to set the dpi for printing purposes

There should be a way to set any numerical values by typing them in. Sometimes it gets tremendously tedious trying to use the slider back and forth to the number you want (such as RGB values)

There should be a way to crop picture without having to create a mask every single time. 

When importing a photo into an already created project, the photo never appears in it's native resolution but is always shrunk, which is confusing. Why can't it just be imported at native resolution?

In the recent update the canvas size was updated to be up to 10000 pixels, when I tried exporting a 6000x4800 picture it exports as 4580x3664 same ratio but smaller resolution. 
This should be fixed. 

There should be a magic wand type tool you see in other programs which select similar color areas

There should be a clone tool as well that you see in other programs that lets you paint a certain area with another part of the picture. (This would be the best addition possible)

There should be a way to translate and rotate something a fixed amount of pixels/degrees without having to drag. It just makes for more precision esp. for this type of application. 

Currently, you can mask something from out wards in, but there is no obvious way to mask something inwards out. (Let's say I wanted to crop out a giant circle in the center of my picture)

There should be a way to make two line segments or curves that are attached tangent to one another (if they aren't already) for the purposes of creating smooth curves. 

This is all the suggestions I have for now. Hopefully these help.

**Comment by sprang** [comment]
Thanks for the suggestions. Would you mind submitting each of these ideas as separate issues? This would make it much easier to discuss and track them.

**Comment by gverma14** [comment]
Ok will do. Thanks for responding!
