### ISSUE TITLE
Feature Request: project manager placement and folders

### ISSUE THREAD

**Issue by gverma14** [sprang/Inkpad#116]
There should be a way to change the order in which projects appear on the main page. Currently, it is sorted by date (most recent created on the bottom). There should be either a set of options or the ability to individually move each project to wherever the user wants it placed or into folders. It would help a lot when grouping together 1st 2nd 3rd drafts while also working on multiple projects at a time.

**Comment by alistairmcmillan** [comment]
Duplicate of #8
