### ISSUE TITLE
Inkpad has stopped exporting to svg

### ISSUE THREAD

**Issue by ghost** [sprang/Inkpad#128]
Hi - urgent fix required. Inkpad not exporting work as svg. Happening on multiple iPads on multiple networks. Working fine until last week. No known changes to devices.

**Comment by alistairmcmillan** [comment]
Tried on various devices and it still works okay for me. Can you tell us what you are doing? Is it one particular file that won't export to SVG? Do you get an error message?

**Comment by ghost** [comment]
Thanks alistair, 
Screenshot of general ipad about settings attached. Also screenshot of what I get when I 'export to svg'.
No error message. Up until about one week ago this process was giving me a rendered version of the drawing to save to photoroll....
Not just my ipad - also happening on a few colleagues' tablets. I am tempted to try deleting and reinstalling - but I assume all the hard work people have put into their drawings will be lost?
Thanks so much for your advice
Emma

![image](https://cloud.githubusercontent.com/assets/7845959/3280767/11e0abb6-f47c-11e3-8024-1ed303cac180.jpg)
![image](https://cloud.githubusercontent.com/assets/7845959/3280768/11e66c0e-f47c-11e3-9c6f-c7e90306648b.jpg)

**Comment by alistairmcmillan** [comment]
I think it's just the preview that doesn't appear. It's still generating the 17KB file. Once you get this screen, click the export button in the top right and it should still let you export.

**Comment by ghost** [comment]
I wish....
Nope - nothing appears in photo roll when I 'save' image anyway.....
:(

Oh - I should add - happening with files that previously worked as well as new ones...

**Comment by alistairmcmillan** [comment]
iOS doesn't natively support SVG files. Try the mail option or saving to something like Dropbox or Google Drive.

**Comment by ghost** [comment]
Weird that previously I was able to preview, then save image (photoroll default), then upload to Dropbox as separate steps with no problems.... 

Having said that...I have just tried out other options as per your suggestion, and those methods seem to work!! You are a life saver :)

That is:
1) 'open in Dropbox' (with no preview ) seems to make it to PC destination with svg characteristics
2) 'Mail' makes it to PC destination ok.

Save as image not working at all, and loss of preview / Dropbox view on ipad, but workaround seems to do the job. Thank you so much for helping me to troubleshoot this...it really was a process of trying every option and then checking what could make it through to PC end.

Weird that behaviour of program changed last week though....gave me a heart attack to think of all the work lost!!

Thanks again
Emma

**Comment by alistairmcmillan** [comment]
Happy to help. Glad to hear that worked for you.

**Comment by cangevine** [comment]
I am unable to open in Google Drive. The blank preview window appears as described above (not a problem), then I use the Share icon and "Open in Google Drive." The Google Drive app switches in -- so far everything seems good -- but then the .svg never appears anywhere. I don't see it in the Google Drive app that just switched in, and I can't find it from a desktop looking for recent files in my Drive.

Any advice?

**Comment by alistairmcmillan** [comment]
Could you create a new issue for this please (https://github.com/sprang/Inkpad/issues/new), cause this is a different problem that seems to be specific to Google Drive. Taking a look just now.

**Comment by StephenERowe** [comment]
Inkpad screen freezes when I send an image via email. It sends, but the screen won't leave the email page, even when I try to cancel the email.
