### ISSUE TITLE
Color slider cut off

### ISSUE THREAD

**Issue by minkalue** [sprang/Inkpad#149]
The top slide in the color slider is cut off. I cannot access the top slider when adjusting the color. This is happening in vertical and horizontal and in InkPad Pro and InkPad 2.0. 
![image](https://cloud.githubusercontent.com/assets/16243960/11725543/480206ae-9f48-11e5-95ee-e7046ddb1c40.png)
![image](https://cloud.githubusercontent.com/assets/16243960/11725544/4819bc9a-9f48-11e5-8845-ff5c44ec1400.png)
![image](https://cloud.githubusercontent.com/assets/16243960/11725545/481f4f98-9f48-11e5-8967-7a33db0c7139.png)
![image](https://cloud.githubusercontent.com/assets/16243960/11725546/48215d06-9f48-11e5-9564-699d9ce1e84d.png)

**Comment by kennethshawfriedman** [comment]
This continues to be an issue. Any updates?

**Comment by alistairmcmillan** [comment]
InkPad Pro and InkPad 2.0 are not official releases. Sorry but you'll need to contact whoever uploaded them to the AppStore for support. Or request a refund from Apple. http://www.imore.com/how-to-get-refund-itunes-app-store

**Comment by alistairmcmillan** [comment]
Closing as duplicate of #133
