### ISSUE TITLE
Clones in App Store unable to connect to Dropbox

### ISSUE THREAD

**Issue by davidfabreguette** [sprang/Inkpad#150]
![image](https://cloud.githubusercontent.com/assets/749900/12072187/d776d958-b0d3-11e5-965e-84eb130893b6.jpeg)
Hi,
I'm getting this error trying to connect my dropbox account to the app.
Anyone ever had this error ??

**Comment by alistairmcmillan** [comment]
Which version of InkPad do you have installed? You'll need to contact however you bought it off of and ask them to fix their code.

**Comment by alistairmcmillan** [comment]
We have no control over the forks in the App Store. Closing issue.
