### ISSUE TITLE
Inkpad 2 has major bugs not pushed to store

### ISSUE THREAD

**Issue by davidfabreguette** [sprang/Inkpad#151]
Hi,
I bougth Inkpad 2 app from the AppStore. (inkPad 2 par Stone Studio Co., Ltd.
https://appsto.re/fr/n6L76.i) but it has several major bugs : 
- popovers heders cropped due to iOS9 
- imposible connection to dropbox (development api key pushed in production)

There was no updates since last november, do you guys have the ability to do something about it ? Looks like the app is not usable for now ... And I think some of those bug are already fixed but just not pushed to the app store,
Thank you !

**Comment by JanX2** [comment]
Could you please complain to Apple about this and ask them to take down the effectively unsupported copy, @davidfabreguette ?

Apparently, the source code lives here:
https://code.csdn.net/voisvous/inkpad2

**Comment by DifferentlyAbled** [comment]
You can get in contact with Steven Sprang here stevesprangdev@gmail.com. H has been contacted about Inkpad 2 as well as other clones on the app store.

**Comment by JanX2** [comment]
Thanks @DifferentlyAbled! Any response?

**Comment by DifferentlyAbled** [comment]
Yes, he has made it clear that he wants apps without repositories or contributions to be removed. @JanX2

**Comment by JanX2** [comment]
I hope that Apple will do something about this. 
@DifferentlyAbled

**Comment by QuetzalPretzel** [comment]
@JanX2 PLEASE BE ADVISED:  The person at stevesprangdev@gmail.com is NOT Steve Sprang.  That is not his email address and the real Steve Sprang would simply post a message here.

John Ciocca, here on GitHub as Ciocca Apps (DifferentlyAbled) who posted that email address bundles an Inkpad clone called Inkbot himself:

The Artistic Bundle by John Ciocca
https://itunes.apple.com/us/app-bundle/the-artistic-bundle/id1006151257?mt=8

Make of that what you will.  Google around and all the dots connect.

**Comment by JanX2** [comment]
@QuetzalPretzel What a weird world we live in. ^^

**Comment by ghost** [comment]
I wonder where Steve is.

Its unfortunate he went away.

I guess this is the power of open source, when people go away, the code is
still there.

I guess the more appropriate thing would be ask Steve if he will allow
others to help on the official build with a time frame, like 15 days and/or
there is no response, then come up with a new new and unlock this to the
open source dev world to make improvements.

That is worst case scenario, but one idea.

Jon

**Comment by alistairmcmillan** [comment]
This is the curse of open source as well.

So many people taking the source that Steve graciously opened up here on GitHub, uploading an app to the store and not releasing their source code changes (if there are any) like the MPL license specifically demands and Steve reiterated in the readme file.

Doesn't help that Apple aren't quick to remove apps that don't comply. https://twitter.com/sprang/status/455766623048056832

**Comment by ghost** [comment]
Maybe we can help Steve that way and make a community version so that when
he comes back its ready for him?

**Comment by rejon** [comment]
Hom = Him ;)

**Comment by alistairmcmillan** [comment]
Steve added me to the project (and others) a while ago. So I can accept pull requests, manage issues, etc here. I've been toying with the idea of uploading a copy of InkPad to the store and continuing development here.

Really would like to hear from Steve first though about what he'd like done.

**Comment by ghost** [comment]
Yes even better! Is there a set of goals or milestone? This js great news.
Ok I should submit a patch!

Jon

**Comment by michaeldugan** [comment]
Someone needs to fix the Dropbox issues.

**Comment by alistairmcmillan** [comment]
@michaeldugan Do you have an Inkpad clone in the App Store?

**Comment by JanX2** [comment]
@alistairmcmillan Yes he does. And sadly, @michaeldugan’s git repos aren't up to spec.

**Comment by alistairmcmillan** [comment]
Just stumbled on another clone. By another developer who has decided to ignore the license and not publish their code changes.

The app store seems to be littered with them.

**Comment by ghost** [comment]
Do we have a list of them? We can then push on apple to remove them to be
compliant.

**Comment by ghost** [comment]
Ok, I propose the best way we can close these issues is to make them more specific.

So the way to close this issue is:
- file a new issue to compare the clones code, harvest anything useful
- Write a legal letter/email and send to apple to shut down this clone
- File other issues, which show excitement, to this issue tracker.
- @alistairmcmillan how about we prepare an InkPad Community Edition and share to the store, once Steve comes back, we can merge efforts into that effor, and then can give access to a few managers of this so there won't be code blocked moving forward? I'm going to file this issue here.

**Comment by ghost** [comment]
InkPad uses the Mozilla Public License. The big thing here we can do is make sure clones do not use the  same name InkPad anywhere in their branding, app, page, etc: https://en.wikipedia.org/wiki/Mozilla_Public_License

However, the best thing to do is be happy and healthy, get a version of InkPad out there that is community version, and then encourage others to send code fixes and more back here. 

We just don't want clones that use InkPad the name and don't follow the social contract of sending code and fixes back to InkPad community, right?

**Comment by alistairmcmillan** [comment]
Hi @michaeldugan,

I have a fix for the Dropbox issue. Make your full repository available (as you are required to by the license) and I'll tell you how to fix the Dropbox code. :)
- Alistair

**Comment by alistairmcmillan** [comment]
We have no control over forks in the App Store. Closing issue.
