### ISSUE TITLE
consider harvesting inkpad 2 clone source code improvements

### ISSUE THREAD

**Issue by ghost** [sprang/Inkpad#153]
consider harvesting any fixes, since the inkpad license permits this.

https://code.csdn.net/voisvous/

@davidfabreguette @alistairmcmillan ping

**Comment by JanX2** [comment]
Sadly, they started a new commit history. We could look at using a git graft to reconnect it.

**Comment by ghost** [comment]
My guess is we ignore the forks on ever level.

**Comment by alistairmcmillan** [comment]
I had a look at the code at the above link late last night. Not many changes in there. So should be trivial to incorporate any useful ones.

**Comment by alistairmcmillan** [comment]
Finally got around to taking a good look at this code. There isn't anything to merge. They basically just took Steve's develop branch, fixed some code problems as prompted by Xcode, changed the version number to 2.0 and published to the App Store.
