### ISSUE TITLE
Dropbox can't be connected

### ISSUE THREAD

**Issue by resimovic** [sprang/Inkpad#164]
I'v got message "Only limited set of users can receive access tokens while this app is in developement mode".
Is this normal state and how to get that token, and how you getin in appstore with developement version of app.

**Comment by alistairmcmillan** [comment]
Can you show us which version of Inkpad you have installed? There are multiple copies of Inkpad in the App Store.

**Comment by resimovic** [comment]
​​

2016-06-30 22:41 GMT+02:00 Alistair McMillan <notifications@github.com>:

> Can you show us which version of Inkpad you have installed? There are
> multiple copies of Inkpad in the App Store.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sprang/Inkpad/issues/164#issuecomment-229782369>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACtndTcbY9YiQnl3C1C1cQUn1rX7Vz-Cks5qRCnjgaJpZM4JCkiC>
> .
>



-- 
Semir Resimović
