### ISSUE TITLE
Not available on Canadian App Store

### ISSUE THREAD

**Issue by ghost** [sprang/Inkpad#166]
When I try to download on my iPad the app store tells me its only available in the US. Has someone got a verion on the Canadian store?

**Comment by alistairmcmillan** [comment]
Try searching for Inkpad by Envoza.

http://inkpad.envoza.com

They're a good team who are improving the app and following the rules that Steve released his code under.

I forgot to mention, Steve's original release isn't available in any stores anymore to the best of my knowledge.
