### ISSUE TITLE
dropbox upload results in an error

### ISSUE THREAD

**Issue by freggala** [sprang/Inkpad#170]
Hello,
I'm using Inkpad 3.0.3 on IOS 11.2.1. When I try to export a bunch of drawings (or even just one), via _**bottom toolbar -> Select -> select drawing(s) -> Dropbox -> SVG -> Upload**_, my attempt fails with the following error message:
"(Upload Problem) 

> There was a problem uploading "name_of_drawing.svg". Check your network connection and try again.

 (Ok-button)". 

Network connectivity works fine and the dropbox app itself can connect to my dropbox account without any problems. Even exporting drawings one by one via 
_**Gallery -> open drawing -> share-icon -> "Export as SVG" -> share-icon -> "Copy to Dropbox" -> Save**_ works ok. It's just really annoying having to do so.

I hope you can help.
 Thanks in advance!

**Comment by alistairmcmillan** [comment]
@freggala Whose version of Inkpad are you using?

**Comment by freggala** [comment]
I'm not an expert, when it comes to using iOS, so it turned out to be a bit tricky to find, what/whose version I actually have. In the app (help) itself it says 3.0.3. but nothing about the issuer but the link in there points me here. Under _**Settings -> General -> iPad Storage -> Inkpad**_ it says Version 3.0.1, Stone Studio Co.Ltd.

**Comment by alistairmcmillan** [comment]
@freggala The person selling that copy of Inkpad seems to have an account here. https://github.com/StoneStudio/Technology-Support/issues Best to open an issue there and let them know about the bug. We don't have any access to their version of the app to fix it here.

**Comment by freggala** [comment]
Thanks for the hint! I just did as you suggested.
