### ISSUE TITLE
Import and Upload - no connection with dropbox 

### ISSUE THREAD

**Issue by lara66** [sprang/Inkpad#171]
Hello,

I‘ve bought the app  Inkpad2. I‘d like to import fonts from dropbox in the app. So I‘ve logged in on dropbox and imported there my fonts. Then I was going back to the app and clicked on the import button. But it doesn‘t work. When I click on the import button, I‘ve got the information that Inkpad is connected with my dropbox.

In the app there are example pictures, so I tried to upload them in my dropbox. I‘ve got the advice that I have to proof my internet connection. 

I‘m very desperate now. I only like to import fonts in the app. Can you help me please? 

Best wishes 
Kristina

**Comment by alistairmcmillan** [comment]
@lara66 The person selling that copy of Inkpad seems to have an account here. https://github.com/StoneStudio/Technology-Support/issues Best to open an issue there and let them know about the bug. We don't have any access to their version of the app to fix it here.
