### ISSUE TITLE
IPad Pro Multitasking Compatibility

### ISSUE THREAD

**Issue by OrigamiEd** [sprang/Inkpad#172]
Request to have iPad Pro multitasking compatibility added (ie. have Inkpad run in one window while something else runs in another window).

Thanks
Ed

OrigamiEd

**Comment by alistairmcmillan** [comment]
Which version of Inkpad are you using right now? Steve's Inkpad isn't available in the store anymore. I'm assuming you're using one of the forks.

Envoza's fork supports the iPad multitaking features.
https://itunes.apple.com/us/app/inkpad-vector-design-illustration/id1057007769?mt=8

**Comment by OrigamiEd** [comment]
Do I have to buy the new version too? Mine is a blue icon not yellow. Will my drawings be compatible?

**Comment by alistairmcmillan** [comment]
@OrigamiEd If you've already bought another fork of Inkpad you could try contacting whoever released that fork, and asking them to add the feature.

But yeah the documents should be compatible between forks of Inkpad.

**Comment by OrigamiEd** [comment]
I’m not sure how to identify the fork i need to post on. How do I do that?

**Comment by OrigamiEd** [comment]
I guess, i am confused about this process. I bought it through the Apple App Store. Shouldn’t the version I bought there be updated by the new version?

**Comment by alistairmcmillan** [comment]
@OrigamiEd I think this used to be easier to find but...

- Open the App Store on your device
- Click on the little icon that represents your account in the top-right corner of the screen
- Click on Purchased
- Either search through the list of your purchased apps or type the name in the search box
- Tap on the app and under the app name it should tell you the person or company you purchased the app from

If you let me know which fork you've installed I might be able to tell you more about whether it can be updated to support multitasking and whether your can exchange documents with other forks.

**Comment by OrigamiEd** [comment]
I couldn’t find to old inkpad in the list of apps i purchased on the App Store. I finally gave up and bought the new one. What I need to know is how do I get my diagrams from the old one to the new one. It seems the old one no longer will communicate with Dropbox. Is there a way of moving them around on my iPad so the new version can read them?

**Comment by alistairmcmillan** [comment]
@OrigamiEd Really difficult to know the answer to that question without knowing which fork you have the drawings in. Some forks allow exporting to other apps. Some forks allow exporting to other cloud providers like iCloud or Google Drive.

Best guesses (assuming this is one of the forks where someone didn't make many changes)...

* Tap on "Select" in the bottom-right corner of the gallery view
* Select a draw you want to export
* Tap on "Email" in the bottom-left corner of the gallery view
* Select "Inkpad" as the format and "Send"

This should hopefully let you export the files as attachments to emails. From there you can drop them in your Dropbox, or even just open them in another Inkpad fork.

Let us know how you get on.

**Comment by OrigamiEd** [comment]
Well, the email option works for moving the images over. However, I can only email 5 at a time...gonna take some time. 

Thank you for helping me...best of luck with future dev efforts.
