### ISSUE TITLE
Add import from photos and from clipboard

### ISSUE THREAD

**Issue by RussellWarshay** [sprang/Inkpad#18]
Currently it is possible to start from a picture taken from the camera.  There does not seem to be a way to start from selecting a photo, or from the clipboard.  Adding these abilities would be appreciated.

**Comment by samgreen** [comment]
It should be noted that it's pretty easy to start a new drawing and then immediately import a photo using the top right photo button. Additionally pasting an image at start would be an easy way to accomplish this.

**Comment by sprang** [comment]
I can easily add a photo import button in the Gallery. I'm not sure what the UI would look like for creating a new drawing from the pasteboard though.

**Comment by samgreen** [comment]
New ->
  From Photo Library
  From Clipboard

Possibly something like that? Just make it smart enough to only show the first option based on the mime type of the pasteboard contents.

**Comment by sprang** [comment]
You can now import from the photo gallery in the browser. I'm not too concerned about the clipboard case.
