### ISSUE TITLE
Add support for document sharing

### ISSUE THREAD

**Issue by gandreoliva** [sprang/Inkpad#19]
Inkpad is excellent!

Please consider adding support for "Open in..." In order to export SVG/PDF to other apps. Email and Dropbox are not enough, because they depend on a working internet connection, and SVGs can get pretty heavy.

**Comment by RussellWarshay** [comment]
This would be a nice addition.

**Comment by samgreen** [comment]
This can be accomplished with the UIDocumentInteractionController on iOS.

**Comment by sprang** [comment]
It's a good idea and I'd be happy to take a patch for this... I probably won't get to it for a while if it's left to me.

**Comment by sprang** [comment]
This is now implemented in the canvas view (it will be in the next update). Could conceivably add it in the gallery too, but I think this is sufficient.
