### ISSUE TITLE
Flood fill vector implementation

### ISSUE THREAD

**Issue by aksonov** [sprang/Inkpad#21]
Inkscape have this nice feature and it works really good. Could it be implemented within InkPad? It will simplify UI a lot also - we could remove 'fill path with color/gradient' and leave only thickness and colour as separate characteristics of the path. Currently it is quite difficult to work with filling.

**Comment by sprang** [comment]
I'm not really sure what you're getting at here. I haven't spent much time playing with Inkscape. 

I don't really see how fills are any harder to deal with than strokes? They're actually much simpler in terms of attributes.

**Comment by aksonov** [comment]
If it would have flood fill function, it would be much easier to use for children for example. They just use free pen, and then want to add colour. Currently it is not possible to do - need to define strokes in smart way.

**Comment by sprang** [comment]
Sorry, but I think this is unlikely to be implemented.
