### ISSUE TITLE
NSString properties are declared strong instead of copy

### ISSUE THREAD

**Issue by samgreen** [sprang/Inkpad#25]
NSString properties should almost always be copy instead of strong, due to the way objective C handles strings.

**Comment by sprang** [comment]
What's the issue? Mutating out from under you?

**Comment by samgreen** [comment]
No issue, this just might be a problem if an NSMutableString is set for the value of the property. But it seems like you're aware of this based on your response. Loving the code base, thanks for open sourcing!

**Comment by sprang** [comment]
Thanks for the patch. :-)
