### ISSUE TITLE
Add Support for Jot Stylus

### ISSUE THREAD

**Issue by macbeta** [sprang/Inkpad#27]
Please add support for Jot Stylus :)

**Comment by sprang** [comment]
Can you be more specific about what you want Inkpad to support? The stylus should just work as is. There's not currently any feature in Inkpad that could make use of pressure data.

**Comment by macbeta** [comment]
Hi sure its mainly the Palm rejection stuff that I'm interested in, gives a nice natural feel when working.

**Comment by intz** [comment]
This new Adonit jot script stylus seems to be really good one. They have dev SDK what enables palm rejection: http://adonit.net/jot/script/

**Comment by 2grep** [comment]
Regarding the jot script, thanks forte link, I was extremely exactitude to see that. But too many styluses have left me jaded, so I checked the reviews. The reviews are lack-luster
- http://shannonstacey.com/2013/11/the-jot-script-evernote-edition-stylus/
- http://www.tuaw.com/2013/11/04/hands-on-with-the-adonit-jot-script-stylus-for-ios-evernote-e/

Cool if inkpad incorporates it, but, if I were managing the development, I don't think I'd spend to much effort on this particular product. No yet anyway.

**Comment by sprang** [comment]
I don't think I want to integrate stylus support just for palm rejection. Integrating 3rd party pens is fairly annoying (there are a number of them). I'll reconsider this if we ever add any pressure-related features.
