### ISSUE TITLE
Register with safari as an app you can open svg in

### ISSUE THREAD

**Issue by 2grep** [sprang/Inkpad#31]
This would make it much easier to grab an svg off Wikipedia and edit it (usually to re-upload it)

Would expect the same functionality as when opening a PDF: Safari offers the option of opening in other apps, like Papers2, Dropbox, etc.

**Comment by alistairmcmillan** [comment]
Unfortunately Safari doesn't seem to treat SVG files in the same way it does PDF files. The default sharing panel in the toolbar seems to be limited for both types of files compared to the way the default sharing panel works in other applications. For PDF files Safari displays a dropdown toolbar in the content area that offers an "Open In..." menu. Unfortunately it doesn't offer the same dropdown toolbar for SVG files. So I can't see how to get files from Safari to Inkpad.

Similarly Google Chrome doesn't use the default sharing panel. They have their own custom built one.

However other applications like Dropbox, Mailbox, Apple's Mail, Textastic, etc will all offer Inkpad as an option for handling SVG files with this change.

**Comment by sprang** [comment]
Integrated.
