### ISSUE TITLE
Radial Gradient Control Handles

### ISSUE THREAD

**Issue by rletkeman** [sprang/Inkpad#43]
Please consider reversing the initial start and end positions of a radial gradient when it is applied to an object. I realize this may seem trivial, but as an Inkpad user, I find I am usually reversing the position of the control handles so that the start of the gradient is located at the center of an object. Graphic attached to further illustrate my proposed request. 
![radialgradient](https://f.cloud.github.com/assets/5980741/1601703/4547c9b6-538d-11e3-8fb5-5b6be568e382.jpg)

**Comment by sprang** [comment]
This should be easy to fix. I'll take a look today.

**Comment by sprang** [comment]
Actually, I'm not sure what you mean here Ron. When I apply a gradient to a shape, it initially runs from the left edge of the shape to the right edge. Which isn't quite the problem you're describing. I could make the initial start point centered if the gradient is radial...?

You probably already know this, but you can also reverse the direction of the gradient by swiping over the gradient bar in the fill panel.

**Comment by rletkeman** [comment]
Thanks Steve... my suggestion is to make the initial starting point at the center of an object.
