### ISSUE TITLE
Add snap to object edges

### ISSUE THREAD

**Issue by lukejanicke** [sprang/Inkpad#47]
It seems that objects are not snapping to each others’ edges. This would help me vertically space text objects using the natural line height of fonts. Sorry, I’m not a coder. But a heavy user of Inkpad. Please delete this Issue if it’s already listed and I’ve missed it.

**Comment by lukejanicke** [comment]
For further clarification. Snap to grid and snap to points both work as advertised/expected. However, with only "snap to edges" toggled on, I discern no snapping. Objects don’t snap to the edge of the canvas, nor do objects snap to each others’ vertical or horizontal edge/extremity lines. If I have missed the point somewhere, please comment with an explanation and I’ll delete this Issue. Alternatively, I’d like to hear if anyone can confirm this Issue.

**Comment by sprang** [comment]
Perhaps the option would be better titled "Snap To Path". It only works with the pen tool, the shape creation tools, and the transform tools (when setting the pivot point). Basically, any time the snap can occur by testing a single input point. 

It sounds like you want the behavior I intended with Issue #14, which allow you to dynamically align to the bounding boxes of other objects as you drag.

**Comment by lukejanicke** [comment]
Thanks for that. Yes, Issue #14 is what I'm looking for. And "Snap to Path" also makes sense. I see it working that way now and I’ll be able to employ it in my work.
