### ISSUE TITLE
Add mirror functionality

### ISSUE THREAD

**Issue by 6112115** [sprang/Inkpad#51]
Hi All,

Would it be possible to add the mirror functionality that other vector programs have?
So if you change something on one side, it changes it on the other?

Thanks!
6112115

**Comment by sprang** [comment]
I think this is unlikely to be added to Inkpad. It's easy to select a set of shapes, duplicate them and flip/reflect them already. I'm actually not sure I've ever seen a mirror feature in a vector app... which one are you thinking of?
