### ISSUE TITLE
Center point on shapes for resizing

### ISSUE THREAD

**Issue by appledogx** [sprang/Inkpad#52]
Great app, but I sometimes find it frustrating to resize a rectangle. I must move each side's corner point by itself. I'd love to see a point on the center of rectangles, or other shapes for that matter, to be able to resize the shapes or rectangles uniformly without moving each vertex separately.

**Comment by sprang** [comment]
I'm not sure I understand the request. Why not resize using the scale tool? You can get uniform scaling as described in the in-app help.

**Comment by appledogx** [comment]
If you wish to resize in one direction, you end up dragging corners separately. Most of the time I'm not trying to rescale an object (in two dimensions, but re-align one side of a rectangle, for instance). Currently, I have to do it corner by corner unless there's something I'm not getting.

**Comment by sprang** [comment]
You can select multiple anchors at once using the "plus arrow" if that helps. With the scale tool, you can move the pivot point to one corner and get a non-uniform scale by touching the screen with another finger while dragging. That might not be very accurate though.
