### ISSUE TITLE
"ALT" hotbutton

### ISSUE THREAD

**Issue by 32Beat** [sprang/Inkpad#59]
Instead of having to select the +selection tool for selecting multiple elements, it might be useful to hold an "ALT" hotbutton that enables temporary special functions. This button could be placed left or right depending on the user's handedness.

**Comment by sprang** [comment]
I'm not crazy about this idea. I think it adds clutter; you end up with another pseudo tool palette. If you have to tap another button to get the special mode, why not just tap the other tool button that's already there?

By the way, many tools in Inkpad use a secondary touch to enable an alternate behavior (this is discussed in the in-app help).
