### ISSUE TITLE
Serious Error: editing gridspacing in dialog

### ISSUE THREAD

**Issue by 32Beat** [sprang/Inkpad#66]
while setting the gridspacing (in the simulator), clicking in the textbox after the first time results in a whole bunch of the following messages:

...: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by sprang** [comment]
I'm not able to reproduce this one. Does it only happen in the simulator for you?

**Comment by 32Beat** [comment]
Happens in simulator only, at the moment. Seems to be something system related, during some animation an object "UICalloutBarBackground" is requested to layout its subviews and attempts to draw in a context created by UIGraphicsBeginImageContextWithOptions.
The internutz mentions this error as well, consensus seems to be that it is indeed system related. 

That said: I do see a lot of code in Inkpad that could use some defensive programming, e.g. checking for nil pointers before using them.
