### ISSUE TITLE
Bug-- drawing content deleted

### ISSUE THREAD

**Issue by hjmpw** [sprang/Inkpad#76]
Hello

I use inkpad at my work place (currently v 1.4.1 on an iPad 2). I occasionally have a problem when backing out of a drawing into the gallery, or renaming a drawing, where the content is lost-- sometimes it is only the last few things added, sometimes it's the whole drawing. I haven't been able to replicate this bug so I don't know what triggers it. Does anyone know of a bug like this? Is there a fix for it?

Thank you

**Comment by sprang** [comment]
This isn't a known bug, but Inkpad 1.4.1 is quite old at this point. The newest version is 1.5.2 (it does require iOS 7).

**Comment by sprang** [comment]
Will reopen if this still happens in the latest version.
