### ISSUE TITLE
Sometimes the SVG importer produces bogus paths

### ISSUE THREAD

**Issue by sprang** [sprang/Inkpad#77]
Here's one that exhibits the problem (the error is obvious):
https://openclipart.org/detail/1033/apple-by-johnny_automatic

**Comment by sprang** [comment]
Here's another one:
https://openclipart.org/detail/87763/funny-bunny-face-by-palomaironique

I've seen a lot of errors in circles, so perhaps there's a problem in the arc code.

**Comment by 32Beat** [comment]
I believe the problem is solved in the new SVG branch update. The path generating code did not properly update internals for sequenced path elements.

**Comment by sprang** [comment]
Fixed with merge 8858a46e920946c90ca50f7a3537e4003b210c49.
