### ISSUE TITLE
Shapetools unavailable on non-retina

### ISSUE THREAD

**Issue by 32Beat** [sprang/Inkpad#79]

**Comment by sprang** [comment]
Do you mean the popover from the tool palette with the star, spiral, etc.? Everything seems okay to me in the simulator. I can look on an iPad 2 later today.

**Comment by 32Beat** [comment]
Ignore. In one of my versions I had more shapetools available and it was trying to preselect that from the user defaults.

**Comment by sprang** [comment]
Anything in the works you might want to get in the next update?

**Comment by 32Beat** [comment]
No, I think it would be more appropriate for a next major version. 

I am working on editable shapes. You can then re-adjust the corner radius for rectangles after the placement. Or increase the number of starpoints etc... I still want to work my way through some more code in order to come up with a reasonable and save implementation path.

**Comment by sprang** [comment]
Sounds good! Would you mind sending me an email? I think these issue comments are the only way I have to communicate with you at the moment.

**Comment by 32Beat** [comment]
e-mail send
