### ISSUE TITLE
Toolpalette position after rotation

### ISSUE THREAD

**Issue by 32Beat** [sprang/Inkpad#80]
When the toolpalette is positioned against the right side of the screen in portrait, then after rotation to landscape it is positioned somewhere halfway the screen.

**Comment by 32Beat** [comment]
This would probably give a reasonable default expected behavior
WDPalette --> initWithFrame

``` c
    [self setAutoresizingMask:
    UIViewAutoresizingFlexibleTopMargin|
    UIViewAutoresizingFlexibleLeftMargin|
    UIViewAutoresizingFlexibleRightMargin|
    UIViewAutoresizingFlexibleBottomMargin];
```

**Comment by sprang** [comment]
Yep, that looks good in the simulator. I'll check in the change when I have a chance to test it on the device.
