### ISSUE TITLE
Broken gradient when importing linked SVG file

### ISSUE THREAD

**Issue by sprang** [sprang/Inkpad#81]
https://openclipart.org/people/danko/danko_Friendly_rabbit.svg

The gradient on the shape at the rear of the rabbit has an empty stops array.

**Comment by 32Beat** [comment]
What do you mean by empty stops array? The drawing itself seems to show a correct and editable gradient control? There does seem to be a difference in gamma processing...

**Comment by sprang** [comment]
I added some code to work around this (since it caused a crash when trying to edit the gradient): 04ec98dd50f275a591f55018085f95358304dcf5
