### ISSUE TITLE
Set the <g> Layer ID to the Inkpad LayerName, not "Layer_1", "Layer_2" etc on SVG export

### ISSUE THREAD

**Issue by JohnDuke37** [sprang/Inkpad#90]
When exporting an Inkscape file to SVG, the layers are renamed to "Layer_1", "layer_2" etc. rather than using the inkscape layer name.  The Inkscape layer name is stored as metadata that is ignored by all other Vector graphics programs such as Illustrator.
Please, please just set the <g> ID to the inkscape layer name! If you need to, append an "_1", "_2" to each name to keep them unique.

You will be saving the sanity of many armchair Inkpad lovers like myself!

Example: (please note that I swapped out the GreaterThan and Lessthan with [ and ] so this would post)

How it works now:
[g id="Layer_2" inkpad:layerName="Left leg"]

How it should work:
[g id="Left leg" inkpad:layerName="Left leg"]

**Comment by rhcad** [comment]
Two layers can have the same name in Inkpad now. So the <g> Layer ID will not be uniqued.

**Comment by JohnDuke37** [comment]
Thanks!  This is fantastic news for anyone that uses Inkpad and Illustrator!

**Comment by rhcad** [comment]
Oh, it's not a news yet! I am referring that if the request of you mentioned implemented, the above problems will exist, so it can not be determined implementing the demand. So, either not allow layers of the same name, or allow the same <g> Layer ID in SVG.

**Comment by sprang** [comment]
We could just unique the layer names. So, if you have two layers named "foobar", one becomes "foobar_1". We'd also have to check the SVG spec to see what the rules are for ID strings. It's possible a user editable string wouldn't be a valid ID name for reasons other than uniqueness.

**Comment by JohnDuke37** [comment]
Absolutely - this would do it. 
1.  Use the Inkpad layer name and append a digit to keep is unique as necessary.

**Comment by svachalek** [comment]
(delurking)

The spec for id attributes:
http://www.w3.org/TR/2008/REC-xml-20081126/#NT-Name

**Comment by rhcad** [comment]
Realized it.
