### ISSUE TITLE
An app is more like Inkpad!

### ISSUE THREAD

**Issue by rhcad** [sprang/Inkpad#93]
https://itunes.apple.com/cn/app/!vectorpaint-ipad-shi-liang/id789478884?mt=8

![image](https://f.cloud.github.com/assets/558922/2428661/175d07a6-ac56-11e3-86ae-a255087c6c1f.jpg)

**Comment by 32Beat** [comment]
Search the app store for "vector graphics", several copies will turn up.

**Comment by ghost** [comment]
Can you help us translate inkpad into Chinese?

**Comment by rhcad** [comment]
Yes, I'd like it.

Zhang Yungui

> 在 2014年3月16日，上午12:05，"Jon Phillips" notifications@github.com 写道：
> 
> Can you help us translate inkpad into Chinese? 
>

**Comment by rhcad** [comment]
I'm translating inkpad into Chinese at https://crowdin.net/project/inkpad/zh-CN now.

**Comment by ghost** [comment]
Great!

**Comment by xiezhhw** [comment]
I checked your translations and found a few mistakes. So I  corrected some of them. Check it out on crowdin.net.

**Comment by ghost** [comment]
Cool. Can you guys also translate the main apple store page into chinese?

Jon

**Comment by xiezhhw** [comment]
no problem.  we are now translating the help page.

**Comment by rhcad** [comment]
The main apple store page added: https://crowdin.net/translate/inkpad/51/zhcn-zhcn
We'll translate this page and the [help page](https://crowdin.net/translate/inkpad/50/zhcn-zhcn) these days.

**Comment by ghost** [comment]
Amazing! Thanks

**Comment by rhcad** [comment]
The [main apple store page](https://crowdin.net/proofread/inkpad/51/zhcn-zhcn) has been translated.

**Comment by rhcad** [comment]
We have completed the translation. Please see #100.

**Comment by sprang** [comment]
I complained about a bunch of these clones to Apple, since almost all of them are violating the license, but so far no action has been taken. I will ping Apple again. Thanks for doing the translation! I will try to take a look at the patch today.

**Comment by rhcad** [comment]
You should probably choose GPL licence to avoid being cloned.

**Comment by sprang** [comment]
I would have chosen the GPL, but my understanding is that this would make it difficult/impossible to accept patches, since the GPL and the App Store are incompatible. I chose the MPL because it's a bit more flexible, but still a copyleft license. Technically the clones are allowed, but they have to publish the Inkpad code (including their changes).

**Comment by sprang** [comment]
Anyway, the cat's out of the bag now.
